services:
     
    spark-master:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spark-master
      hostname: spark-master
      ports:
        - "9090:8080"
        - "7077:7077"
      expose: 
        - "7077"
      environment:
        - SPARK_USER=spark
        - SPARK_MASTER_PORT=7077
        - SPARK_MASTER_WEBUI_PORT=8080
      command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master"
      volumes:
        - ./scripts:/opt/spark/data_processing
        - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
        - ./conf/log4j.properties:/opt/spark/conf/log4j.properties
      networks:
        - spark-network

    spark-worker-1:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spark-worker-1
      hostname: spark-worker-1
      ports:
        - "8082:8081" 
      depends_on:
        - spark-master
      command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
      environment:
        - SPARK_MODE=worker
        - SPARK_WORKER_WEBUI_PORT=8081
        - SPARK_WORKER_MEMORY=1G
        - SPARK_WORKER_CORES=2
      networks:
        - spark-network